title: "Bernard Joseph Oyakhilome â€“ Data Analyst / BI Analyst"

description: >
  ğŸ’¼ Excel | SQL | Power BI  
  
  ğŸ” Passionate about turning raw data into actionable insights that drive decision-making.

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
